version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql-school
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sql12
      MYSQL_DATABASE: schoolDb
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
